version: '3'

services:

  db:
    image: timescale/timescaledb:latest-pg12
    container_name: db_timescale
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: . # Use an image built from Dockerfile in current dir.
      dockerfile: Dockerfile
    ports: # forward port from container to host machine
      - "8081:8081"
    restart: unless-stopped
    depends_on: # This service depends on db service. Start that first.
      - db